ALTER TABLE usuarios ADD CONSTRAINT FK_Rol FOREIGN KEY(idRol) REFERENCES roles(idRol) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE servidor ADD CONSTRAINT FK_estatuServidor FOREIGN KEY(idEstatus) REFERENCES estatus(idEstatus) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE servidor ADD CONSTRAINT FK_cuenta FOREIGN KEY(idCuenta) REFERENCES cuentas(idCuenta) ON UPDATE CASCADE ON DELETE RESTRICT;

alter table anime ADD CONSTRAINT FK_status FOREIGN KEY(idEstatus) REFERENCES estatus(idEstatus) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE temporada ADD CONSTRAINT FK_anime FOREIGN KEY(idAnime) REFERENCES anime(idAnime) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE temporada ADD CONSTRAINT FK_statusTem FOREIGN KEY(idEstatus) REFERENCES estatus(idEstatus) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE cuentas ADD CONSTRAINT FK_tipoCueta FOREIGN KEY(idTipocuenta) REFERENCES tipoCuenta(idTipocuenta) ON UPDATE CASCADE ON DELETE RESTRICT;
alter table cuentas ADD CONSTRAINT FK_status_cuenta FOREIGN KEY(idEstatus) REFERENCES estatus(idEstatus) ON UPDATE CASCADE ON DELETE RESTRICT;
